import { Car, Home, List, NotepadText, Settings, UserCheck, Users } from "lucide-react";

import ProfileImage from "@/assets/profile-image.jpg";

export const navbarLinks = [
    {
        title: "Dashboard",
        links: [
            {
                label: "Dashboard",
                icon: Home,
                path: "/dashboard",
            },
            {
                label: "Users management",
                icon: Users,
                path: "/dashboard/users",
            },
            {
                label: "Car management",
                icon: Car,
                path: "/dashboard/cars",
            },
        ],
    },
    {
        title: "Report",
        links: [
            {
                label: "Reported Car",
                icon: List,
                path: "/dashboard/settings",
            },
            {
                label: "Reported Users",
                icon: List,
                path: "/dashboard/settings",
            },
        ],
    },
    {
        title: "Settings",
        links: [
            {
                label: "Settings",
                icon: Settings,
                path: "/dashboard/settings",
            },
        ],
    },
];

export const userGrowthData = [
    { month: "Jan", users: 120 },
    { month: "Feb", users: 180 },
    { month: "Mar", users: 250 },
    { month: "Apr", users: 310 },
    { month: "May", users: 400 },
    { month: "Jun", users: 500 },
    { month: "Jul", users: 680 },
    { month: "Aug", users: 820 },
    { month: "Sep", users: 1000 },
];

export const recentSignupsData = [
    {
        id: 1,
        name: "John Doe",
        email: "john@email.com",
        image: ProfileImage,
        signupDate: "Sep 5, 2025",
        status: "Pending",
    },
    {
        id: 2,
        name: "Maria Santos",
        email: "maria@email.com",
        image: ProfileImage,
        signupDate: "Sep 4, 2025",
        status: "Verified",
    },
    {
        id: 3,
        name: "Alex Rivera",
        email: "alex@email.com",
        image: ProfileImage,
        signupDate: "Sep 3, 2025",
        status: "Pending",
    },
    {
        id: 4,
        name: "Sarah Cruz",
        email: "sarah@email.com",
        image: ProfileImage,
        signupDate: "Sep 2, 2025",
        status: "Verified",
    },
];

export const recentSalesData = [
    {
        id: 1,
        name: "Olivia Martin",
        email: "olivia.martin@email.com",
        image: ProfileImage,
        total: 1500,
    },
    {
        id: 2,
        name: "James Smith",
        email: "james.smith@email.com",
        image: ProfileImage,
        total: 2000,
    },
    {
        id: 3,
        name: "Sophia Brown",
        email: "sophia.brown@email.com",
        image: ProfileImage,
        total: 4000,
    },
    {
        id: 4,
        name: "Noah Wilson",
        email: "noah.wilson@email.com",
        image: ProfileImage,
        total: 3000,
    },
    {
        id: 5,
        name: "Emma Jones",
        email: "emma.jones@email.com",
        image: ProfileImage,
        total: 2500,
    },
    {
        id: 6,
        name: "William Taylor",
        email: "william.taylor@email.com",
        image: ProfileImage,
        total: 4500,
    },
    {
        id: 7,
        name: "Isabella Johnson",
        email: "isabella.johnson@email.com",
        image: ProfileImage,
        total: 5300,
    },
];

export const verifiedUsers = [
    {
        number: 1,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "3",
        status: "Active",
    },
    {
        number: 2,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "3",
        status: "Active",
    },
    {
        number: 3,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "3",
        status: "Active",
    },
    {
        number: 4,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "3",
        status: "Active",
    },
    {
        number: 5,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "-",
        status: "Active",
    },
    {
        number: 6,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "-",
        status: "Active",
    },
    {
        number: 7,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "-",
        status: "Active",
    },
    {
        number: 8,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "3",
        status: "Active",
    },
    {
        number: 9,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "3",
        status: "Active",
    },
    {
        number: 10,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        verifiedOn: "Sep 2, 2025",
        carsListed: "3",
        status: "Active",
    },
];

export const pendingCars = [
    {
        number: 1,
        ownerName: "John Doe",
        ownerEmail: "john@email.com",
        car: "Toyota Vios 2021",
        category: "Sedan",
        plateNumber: "ABC-1234",
        documents: "Submitted",
        photos: "3",
        dateSubmitted: "Sep 2, 2025",
        status: "Pending",
    },
    {
        number: 2,
        ownerName: "Maria Santos",
        ownerEmail: "maria@email.com",
        car: "Honda Civic 2020",
        category: "Sedan",
        plateNumber: "XYZ-5678",
        documents: "Missing Insurance",
        photos: "5",
        dateSubmitted: "Sep 3, 2025",
        status: "Pending",
    },
    {
        number: 3,
        ownerName: "Alex Rivera",
        ownerEmail: "alex@email.com",
        car: "Mitsubishi Montero 2019",
        category: "SUV",
        plateNumber: "LMN-4321",
        documents: "Submitted",
        photos: "4",
        dateSubmitted: "Sep 4, 2025",
        status: "Pending",
    },
    {
        number: 4,
        ownerName: "Sarah Cruz",
        ownerEmail: "sarah@email.com",
        car: "Nissan Almera 2022",
        category: "Sedan",
        plateNumber: "QWE-9876",
        documents: "Submitted",
        photos: "6",
        dateSubmitted: "Sep 5, 2025",
        status: "Pending",
    },
    {
        number: 5,
        ownerName: "Mark Lopez",
        ownerEmail: "mark@email.com",
        car: "Ford Ranger 2021",
        category: "Pickup",
        plateNumber: "TRK-2021",
        documents: "Submitted",
        photos: "5",
        dateSubmitted: "Sep 5, 2025",
        status: "Pending",
    },
    {
        number: 6,
        ownerName: "Jenny Tan",
        ownerEmail: "jenny@email.com",
        car: "Hyundai Accent 2020",
        category: "Sedan",
        plateNumber: "CAR-2020",
        documents: "Submitted",
        photos: "3",
        dateSubmitted: "Sep 6, 2025",
        status: "Pending",
    },
    {
        number: 7,
        ownerName: "David Kim",
        ownerEmail: "david@email.com",
        car: "Chevrolet Trailblazer 2018",
        category: "SUV",
        plateNumber: "SUV-8899",
        documents: "Missing OR/CR",
        photos: "2",
        dateSubmitted: "Sep 6, 2025",
        status: "Pending",
    },
    {
        number: 8,
        ownerName: "Ella Garcia",
        ownerEmail: "ella@email.com",
        car: "Kia Stonic 2022",
        category: "Crossover",
        plateNumber: "CRO-2211",
        documents: "Submitted",
        photos: "5",
        dateSubmitted: "Sep 6, 2025",
        status: "Pending",
    },
    {
        number: 9,
        ownerName: "Carlos Reyes",
        ownerEmail: "carlos@email.com",
        car: "Toyota Fortuner 2019",
        category: "SUV",
        plateNumber: "FOR-2019",
        documents: "Submitted",
        photos: "6",
        dateSubmitted: "Sep 7, 2025",
        status: "Pending",
    },
    {
        number: 10,
        ownerName: "Angela Cruz",
        ownerEmail: "angela@email.com",
        car: "Mazda 3 2021",
        category: "Sedan",
        plateNumber: "MAZ-1234",
        documents: "Submitted",
        photos: "4",
        dateSubmitted: "Sep 7, 2025",
        status: "Pending",
    },
];

export const verifiedCars = [
    {
        number: 1,
        ownerName: "John Doe",
        ownerEmail: "john@email.com",
        car: "Toyota Vios 2021",
        category: "Sedan",
        plateNumber: "ABC-1234",
        documents: "Verified",
        photos: "3",
        verifiedOn: "Sep 1, 2025",
        status: "Active",
    },
    {
        number: 2,
        ownerName: "Maria Santos",
        ownerEmail: "maria@email.com",
        car: "Honda Civic 2020",
        category: "Sedan",
        plateNumber: "XYZ-5678",
        documents: "Verified",
        photos: "5",
        verifiedOn: "Aug 30, 2025",
        status: "Active",
    },
    {
        number: 3,
        ownerName: "Alex Rivera",
        ownerEmail: "alex@email.com",
        car: "Mitsubishi Montero 2019",
        category: "SUV",
        plateNumber: "LMN-4321",
        documents: "Verified",
        photos: "4",
        verifiedOn: "Aug 28, 2025",
        status: "Active",
    },
    {
        number: 4,
        ownerName: "Sarah Cruz",
        ownerEmail: "sarah@email.com",
        car: "Nissan Almera 2022",
        category: "Sedan",
        plateNumber: "QWE-9876",
        documents: "Verified",
        photos: "6",
        verifiedOn: "Aug 25, 2025",
        status: "Active",
    },
    {
        number: 5,
        ownerName: "Mark Lopez",
        ownerEmail: "mark@email.com",
        car: "Ford Ranger 2021",
        category: "Pickup",
        plateNumber: "TRK-2021",
        documents: "Verified",
        photos: "5",
        verifiedOn: "Aug 22, 2025",
        status: "Active",
    },
    {
        number: 6,
        ownerName: "Jenny Tan",
        ownerEmail: "jenny@email.com",
        car: "Hyundai Accent 2020",
        category: "Sedan",
        plateNumber: "CAR-2020",
        documents: "Verified",
        photos: "3",
        verifiedOn: "Aug 20, 2025",
        status: "Active",
    },
    {
        number: 7,
        ownerName: "David Kim",
        ownerEmail: "david@email.com",
        car: "Chevrolet Trailblazer 2018",
        category: "SUV",
        plateNumber: "SUV-8899",
        documents: "Verified",
        photos: "2",
        verifiedOn: "Aug 18, 2025",
        status: "Active",
    },
    {
        number: 8,
        ownerName: "Ella Garcia",
        ownerEmail: "ella@email.com",
        car: "Kia Stonic 2022",
        category: "Crossover",
        plateNumber: "CRO-2211",
        documents: "Verified",
        photos: "5",
        verifiedOn: "Aug 15, 2025",
        status: "Active",
    },
    {
        number: 9,
        ownerName: "Carlos Reyes",
        ownerEmail: "carlos@email.com",
        car: "Toyota Fortuner 2019",
        category: "SUV",
        plateNumber: "FOR-2019",
        documents: "Verified",
        photos: "6",
        verifiedOn: "Aug 12, 2025",
        status: "Active",
    },
    {
        number: 10,
        ownerName: "Angela Cruz",
        ownerEmail: "angela@email.com",
        car: "Mazda 3 2021",
        category: "Sedan",
        plateNumber: "MAZ-1234",
        documents: "Verified",
        photos: "4",
        verifiedOn: "Aug 10, 2025",
        status: "Active",
    },
];

export const topProducts = [
    {
        number: 1,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 2,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 3,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 4,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 5,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 6,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 7,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 8,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 9,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
    {
        number: 10,
        name: "John Doe",
        image: ProfileImage,
        email: "jhon@email.com",
        role: "User",
        docs: "License ID",
        signupDate: "Sep 5, 2025",
    },
];
